# docker compose up postgres-db-nestjs -d (the flag -d make it run on the background)
version: '3.8'
services:
  # The name of the container
  postgres-db-nestjs:
    image: postgres:13
    # This binds port 5432 inside the Docker container to port 5434 on the host machine.
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123.
      POSTGRES_DB: nest
